# Generated by Django 4.1.2 on 2022-10-14 13:36

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(validators=[things.models.validate_number])),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
